-- sqltemplate-queries
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,role VARCHAR(20) DEFAULT 'user',is_active BOOLEAN DEFAULT true,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_log(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id),action VARCHAR(100) NOT NULL,details JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_audit_user ON audit_log(user_id);
